name: TAG Leadership Nomination
description: Nominate a TAG Chair or Technical Leader
title: "[VOTE]: "
body:
- type: input
  id: TAG
  attributes: 
    label: TAG
    description: ["TAG App Delivery", "TAG Contributor Strategy", "TAG Environmental Sustainability", "TAG Network", "TAG Observability", "TAG Runtime", "TAG Security", "TAG Storage"]
  validations:
    required: true
- type: textarea
  id: position
  attributes:
    label: Position
    description: ["TAG Chair", "Technical Leader"]
  validations:
    required: true
- type: textarea
  id: name
  attributes:
    label: Name
    description: Name and Github handle of nominee
  validations:
    required: true
- type: textarea
  id: motivation
  attributes:
    label: Motivation & Additional Information
    description: Please provide a motivation why the nominee is a suitable candidate for the position.
  validations:
    required: true
    